//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("CmkFurnituresDbModel", "FK_Authors_Admins", "Admin", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(CmkFurnitures.Domain.Admin), "Author", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(CmkFurnitures.Domain.Author), true)]
[assembly: EdmRelationshipAttribute("CmkFurnituresDbModel", "FK_Articles_Authors1", "Author", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(CmkFurnitures.Domain.Author), "Article", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(CmkFurnitures.Domain.Article), true)]
[assembly: EdmRelationshipAttribute("CmkFurnituresDbModel", "FK_Furnitures_Designers", "Designer", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(CmkFurnitures.Domain.Designer), "Furniture", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(CmkFurnitures.Domain.Furniture), true)]
[assembly: EdmRelationshipAttribute("CmkFurnituresDbModel", "FK_Furnitures_FurnitureType", "FurnitureType", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(CmkFurnitures.Domain.FurnitureType), "Furniture", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(CmkFurnitures.Domain.Furniture), true)]
[assembly: EdmRelationshipAttribute("CmkFurnituresDbModel", "FK_ImageSizes_Images", "Image", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(CmkFurnitures.Domain.Image), "ImageSize", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(CmkFurnitures.Domain.ImageSize), true)]
[assembly: EdmRelationshipAttribute("CmkFurnituresDbModel", "FurnitureImages", "Furniture", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(CmkFurnitures.Domain.Furniture), "Image", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(CmkFurnitures.Domain.Image))]

#endregion

namespace CmkFurnitures.Domain
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class CmkFurnituresDbEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new CmkFurnituresDbEntities object using the connection string found in the 'CmkFurnituresDbEntities' section of the application configuration file.
        /// </summary>
        public CmkFurnituresDbEntities() : base("name=CmkFurnituresDbEntities", "CmkFurnituresDbEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new CmkFurnituresDbEntities object.
        /// </summary>
        public CmkFurnituresDbEntities(string connectionString) : base(connectionString, "CmkFurnituresDbEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new CmkFurnituresDbEntities object.
        /// </summary>
        public CmkFurnituresDbEntities(EntityConnection connection) : base(connection, "CmkFurnituresDbEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Admin> Admins
        {
            get
            {
                if ((_Admins == null))
                {
                    _Admins = base.CreateObjectSet<Admin>("Admins");
                }
                return _Admins;
            }
        }
        private ObjectSet<Admin> _Admins;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Article> Articles
        {
            get
            {
                if ((_Articles == null))
                {
                    _Articles = base.CreateObjectSet<Article>("Articles");
                }
                return _Articles;
            }
        }
        private ObjectSet<Article> _Articles;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Author> Authors
        {
            get
            {
                if ((_Authors == null))
                {
                    _Authors = base.CreateObjectSet<Author>("Authors");
                }
                return _Authors;
            }
        }
        private ObjectSet<Author> _Authors;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Designer> Designers
        {
            get
            {
                if ((_Designers == null))
                {
                    _Designers = base.CreateObjectSet<Designer>("Designers");
                }
                return _Designers;
            }
        }
        private ObjectSet<Designer> _Designers;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Furniture> Furnitures
        {
            get
            {
                if ((_Furnitures == null))
                {
                    _Furnitures = base.CreateObjectSet<Furniture>("Furnitures");
                }
                return _Furnitures;
            }
        }
        private ObjectSet<Furniture> _Furnitures;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<FurnitureType> FurnitureTypes
        {
            get
            {
                if ((_FurnitureTypes == null))
                {
                    _FurnitureTypes = base.CreateObjectSet<FurnitureType>("FurnitureTypes");
                }
                return _FurnitureTypes;
            }
        }
        private ObjectSet<FurnitureType> _FurnitureTypes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Image> Images
        {
            get
            {
                if ((_Images == null))
                {
                    _Images = base.CreateObjectSet<Image>("Images");
                }
                return _Images;
            }
        }
        private ObjectSet<Image> _Images;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ImageSize> ImageSizes
        {
            get
            {
                if ((_ImageSizes == null))
                {
                    _ImageSizes = base.CreateObjectSet<ImageSize>("ImageSizes");
                }
                return _ImageSizes;
            }
        }
        private ObjectSet<ImageSize> _ImageSizes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Subscriber> Subscribers
        {
            get
            {
                if ((_Subscribers == null))
                {
                    _Subscribers = base.CreateObjectSet<Subscriber>("Subscribers");
                }
                return _Subscribers;
            }
        }
        private ObjectSet<Subscriber> _Subscribers;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Admins EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAdmins(Admin admin)
        {
            base.AddObject("Admins", admin);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Articles EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToArticles(Article article)
        {
            base.AddObject("Articles", article);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Authors EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAuthors(Author author)
        {
            base.AddObject("Authors", author);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Designers EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToDesigners(Designer designer)
        {
            base.AddObject("Designers", designer);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Furnitures EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToFurnitures(Furniture furniture)
        {
            base.AddObject("Furnitures", furniture);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the FurnitureTypes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToFurnitureTypes(FurnitureType furnitureType)
        {
            base.AddObject("FurnitureTypes", furnitureType);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Images EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToImages(Image image)
        {
            base.AddObject("Images", image);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ImageSizes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToImageSizes(ImageSize imageSize)
        {
            base.AddObject("ImageSizes", imageSize);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Subscribers EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSubscribers(Subscriber subscriber)
        {
            base.AddObject("Subscribers", subscriber);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CmkFurnituresDbModel", Name="Admin")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Admin : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Admin object.
        /// </summary>
        /// <param name="adminId">Initial value of the AdminId property.</param>
        /// <param name="userName">Initial value of the UserName property.</param>
        /// <param name="password">Initial value of the Password property.</param>
        /// <param name="isSystemUser">Initial value of the IsSystemUser property.</param>
        public static Admin CreateAdmin(global::System.Int32 adminId, global::System.String userName, global::System.String password, global::System.Boolean isSystemUser)
        {
            Admin admin = new Admin();
            admin.AdminId = adminId;
            admin.UserName = userName;
            admin.Password = password;
            admin.IsSystemUser = isSystemUser;
            return admin;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AdminId
        {
            get
            {
                return _AdminId;
            }
            set
            {
                if (_AdminId != value)
                {
                    OnAdminIdChanging(value);
                    ReportPropertyChanging("AdminId");
                    _AdminId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("AdminId");
                    OnAdminIdChanged();
                }
            }
        }
        private global::System.Int32 _AdminId;
        partial void OnAdminIdChanging(global::System.Int32 value);
        partial void OnAdminIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String UserName
        {
            get
            {
                return _UserName;
            }
            set
            {
                OnUserNameChanging(value);
                ReportPropertyChanging("UserName");
                _UserName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("UserName");
                OnUserNameChanged();
            }
        }
        private global::System.String _UserName;
        partial void OnUserNameChanging(global::System.String value);
        partial void OnUserNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private global::System.String _Password;
        partial void OnPasswordChanging(global::System.String value);
        partial void OnPasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsSystemUser
        {
            get
            {
                return _IsSystemUser;
            }
            set
            {
                OnIsSystemUserChanging(value);
                ReportPropertyChanging("IsSystemUser");
                _IsSystemUser = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsSystemUser");
                OnIsSystemUserChanged();
            }
        }
        private global::System.Boolean _IsSystemUser;
        partial void OnIsSystemUserChanging(global::System.Boolean value);
        partial void OnIsSystemUserChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CmkFurnituresDbModel", "FK_Authors_Admins", "Author")]
        public Author Author
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Author>("CmkFurnituresDbModel.FK_Authors_Admins", "Author").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Author>("CmkFurnituresDbModel.FK_Authors_Admins", "Author").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Author> AuthorReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Author>("CmkFurnituresDbModel.FK_Authors_Admins", "Author");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Author>("CmkFurnituresDbModel.FK_Authors_Admins", "Author", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CmkFurnituresDbModel", Name="Article")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Article : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Article object.
        /// </summary>
        /// <param name="articleId">Initial value of the ArticleId property.</param>
        /// <param name="title">Initial value of the Title property.</param>
        /// <param name="creationDate">Initial value of the CreationDate property.</param>
        /// <param name="text">Initial value of the Text property.</param>
        /// <param name="authorId">Initial value of the AuthorId property.</param>
        public static Article CreateArticle(global::System.Int32 articleId, global::System.String title, global::System.DateTime creationDate, global::System.String text, global::System.Int32 authorId)
        {
            Article article = new Article();
            article.ArticleId = articleId;
            article.Title = title;
            article.CreationDate = creationDate;
            article.Text = text;
            article.AuthorId = authorId;
            return article;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ArticleId
        {
            get
            {
                return _ArticleId;
            }
            set
            {
                if (_ArticleId != value)
                {
                    OnArticleIdChanging(value);
                    ReportPropertyChanging("ArticleId");
                    _ArticleId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ArticleId");
                    OnArticleIdChanged();
                }
            }
        }
        private global::System.Int32 _ArticleId;
        partial void OnArticleIdChanging(global::System.Int32 value);
        partial void OnArticleIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime CreationDate
        {
            get
            {
                return _CreationDate;
            }
            set
            {
                OnCreationDateChanging(value);
                ReportPropertyChanging("CreationDate");
                _CreationDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreationDate");
                OnCreationDateChanged();
            }
        }
        private global::System.DateTime _CreationDate;
        partial void OnCreationDateChanging(global::System.DateTime value);
        partial void OnCreationDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Text
        {
            get
            {
                return _Text;
            }
            set
            {
                OnTextChanging(value);
                ReportPropertyChanging("Text");
                _Text = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Text");
                OnTextChanged();
            }
        }
        private global::System.String _Text;
        partial void OnTextChanging(global::System.String value);
        partial void OnTextChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AuthorId
        {
            get
            {
                return _AuthorId;
            }
            set
            {
                OnAuthorIdChanging(value);
                ReportPropertyChanging("AuthorId");
                _AuthorId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AuthorId");
                OnAuthorIdChanged();
            }
        }
        private global::System.Int32 _AuthorId;
        partial void OnAuthorIdChanging(global::System.Int32 value);
        partial void OnAuthorIdChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CmkFurnituresDbModel", "FK_Articles_Authors1", "Author")]
        public Author Author
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Author>("CmkFurnituresDbModel.FK_Articles_Authors1", "Author").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Author>("CmkFurnituresDbModel.FK_Articles_Authors1", "Author").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Author> AuthorReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Author>("CmkFurnituresDbModel.FK_Articles_Authors1", "Author");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Author>("CmkFurnituresDbModel.FK_Articles_Authors1", "Author", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CmkFurnituresDbModel", Name="Author")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Author : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Author object.
        /// </summary>
        /// <param name="firstName">Initial value of the FirstName property.</param>
        /// <param name="lastName">Initial value of the LastName property.</param>
        /// <param name="adminId">Initial value of the AdminId property.</param>
        public static Author CreateAuthor(global::System.String firstName, global::System.String lastName, global::System.Int32 adminId)
        {
            Author author = new Author();
            author.FirstName = firstName;
            author.LastName = lastName;
            author.AdminId = adminId;
            return author;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FirstName
        {
            get
            {
                return _FirstName;
            }
            set
            {
                OnFirstNameChanging(value);
                ReportPropertyChanging("FirstName");
                _FirstName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FirstName");
                OnFirstNameChanged();
            }
        }
        private global::System.String _FirstName;
        partial void OnFirstNameChanging(global::System.String value);
        partial void OnFirstNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LastName
        {
            get
            {
                return _LastName;
            }
            set
            {
                OnLastNameChanging(value);
                ReportPropertyChanging("LastName");
                _LastName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("LastName");
                OnLastNameChanged();
            }
        }
        private global::System.String _LastName;
        partial void OnLastNameChanging(global::System.String value);
        partial void OnLastNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AdminId
        {
            get
            {
                return _AdminId;
            }
            set
            {
                if (_AdminId != value)
                {
                    OnAdminIdChanging(value);
                    ReportPropertyChanging("AdminId");
                    _AdminId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("AdminId");
                    OnAdminIdChanged();
                }
            }
        }
        private global::System.Int32 _AdminId;
        partial void OnAdminIdChanging(global::System.Int32 value);
        partial void OnAdminIdChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CmkFurnituresDbModel", "FK_Authors_Admins", "Admin")]
        public Admin Admin
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Admin>("CmkFurnituresDbModel.FK_Authors_Admins", "Admin").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Admin>("CmkFurnituresDbModel.FK_Authors_Admins", "Admin").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Admin> AdminReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Admin>("CmkFurnituresDbModel.FK_Authors_Admins", "Admin");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Admin>("CmkFurnituresDbModel.FK_Authors_Admins", "Admin", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CmkFurnituresDbModel", "FK_Articles_Authors1", "Article")]
        public EntityCollection<Article> Articles
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Article>("CmkFurnituresDbModel.FK_Articles_Authors1", "Article");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Article>("CmkFurnituresDbModel.FK_Articles_Authors1", "Article", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CmkFurnituresDbModel", Name="Designer")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Designer : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Designer object.
        /// </summary>
        /// <param name="designerId">Initial value of the DesignerId property.</param>
        /// <param name="firstName">Initial value of the FirstName property.</param>
        /// <param name="lastName">Initial value of the LastName property.</param>
        public static Designer CreateDesigner(global::System.Int32 designerId, global::System.String firstName, global::System.String lastName)
        {
            Designer designer = new Designer();
            designer.DesignerId = designerId;
            designer.FirstName = firstName;
            designer.LastName = lastName;
            return designer;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 DesignerId
        {
            get
            {
                return _DesignerId;
            }
            set
            {
                if (_DesignerId != value)
                {
                    OnDesignerIdChanging(value);
                    ReportPropertyChanging("DesignerId");
                    _DesignerId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("DesignerId");
                    OnDesignerIdChanged();
                }
            }
        }
        private global::System.Int32 _DesignerId;
        partial void OnDesignerIdChanging(global::System.Int32 value);
        partial void OnDesignerIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FirstName
        {
            get
            {
                return _FirstName;
            }
            set
            {
                OnFirstNameChanging(value);
                ReportPropertyChanging("FirstName");
                _FirstName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FirstName");
                OnFirstNameChanged();
            }
        }
        private global::System.String _FirstName;
        partial void OnFirstNameChanging(global::System.String value);
        partial void OnFirstNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LastName
        {
            get
            {
                return _LastName;
            }
            set
            {
                OnLastNameChanging(value);
                ReportPropertyChanging("LastName");
                _LastName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("LastName");
                OnLastNameChanged();
            }
        }
        private global::System.String _LastName;
        partial void OnLastNameChanging(global::System.String value);
        partial void OnLastNameChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CmkFurnituresDbModel", "FK_Furnitures_Designers", "Furniture")]
        public EntityCollection<Furniture> Furnitures
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Furniture>("CmkFurnituresDbModel.FK_Furnitures_Designers", "Furniture");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Furniture>("CmkFurnituresDbModel.FK_Furnitures_Designers", "Furniture", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CmkFurnituresDbModel", Name="Furniture")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Furniture : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Furniture object.
        /// </summary>
        /// <param name="partNumber">Initial value of the PartNumber property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="designerId">Initial value of the DesignerId property.</param>
        /// <param name="designYear">Initial value of the DesignYear property.</param>
        /// <param name="price">Initial value of the Price property.</param>
        /// <param name="furnitureTypeId">Initial value of the FurnitureTypeId property.</param>
        /// <param name="profileImageId">Initial value of the ProfileImageId property.</param>
        /// <param name="text">Initial value of the Text property.</param>
        /// <param name="furnitureId">Initial value of the FurnitureId property.</param>
        public static Furniture CreateFurniture(global::System.String partNumber, global::System.String name, global::System.Int32 designerId, global::System.Int32 designYear, global::System.Decimal price, global::System.Int32 furnitureTypeId, global::System.Int32 profileImageId, global::System.String text, global::System.Int32 furnitureId)
        {
            Furniture furniture = new Furniture();
            furniture.PartNumber = partNumber;
            furniture.Name = name;
            furniture.DesignerId = designerId;
            furniture.DesignYear = designYear;
            furniture.Price = price;
            furniture.FurnitureTypeId = furnitureTypeId;
            furniture.ProfileImageId = profileImageId;
            furniture.Text = text;
            furniture.FurnitureId = furnitureId;
            return furniture;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PartNumber
        {
            get
            {
                return _PartNumber;
            }
            set
            {
                OnPartNumberChanging(value);
                ReportPropertyChanging("PartNumber");
                _PartNumber = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("PartNumber");
                OnPartNumberChanged();
            }
        }
        private global::System.String _PartNumber;
        partial void OnPartNumberChanging(global::System.String value);
        partial void OnPartNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 DesignerId
        {
            get
            {
                return _DesignerId;
            }
            set
            {
                OnDesignerIdChanging(value);
                ReportPropertyChanging("DesignerId");
                _DesignerId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DesignerId");
                OnDesignerIdChanged();
            }
        }
        private global::System.Int32 _DesignerId;
        partial void OnDesignerIdChanging(global::System.Int32 value);
        partial void OnDesignerIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 DesignYear
        {
            get
            {
                return _DesignYear;
            }
            set
            {
                OnDesignYearChanging(value);
                ReportPropertyChanging("DesignYear");
                _DesignYear = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DesignYear");
                OnDesignYearChanged();
            }
        }
        private global::System.Int32 _DesignYear;
        partial void OnDesignYearChanging(global::System.Int32 value);
        partial void OnDesignYearChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Price
        {
            get
            {
                return _Price;
            }
            set
            {
                OnPriceChanging(value);
                ReportPropertyChanging("Price");
                _Price = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Price");
                OnPriceChanged();
            }
        }
        private global::System.Decimal _Price;
        partial void OnPriceChanging(global::System.Decimal value);
        partial void OnPriceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 FurnitureTypeId
        {
            get
            {
                return _FurnitureTypeId;
            }
            set
            {
                OnFurnitureTypeIdChanging(value);
                ReportPropertyChanging("FurnitureTypeId");
                _FurnitureTypeId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FurnitureTypeId");
                OnFurnitureTypeIdChanged();
            }
        }
        private global::System.Int32 _FurnitureTypeId;
        partial void OnFurnitureTypeIdChanging(global::System.Int32 value);
        partial void OnFurnitureTypeIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ProfileImageId
        {
            get
            {
                return _ProfileImageId;
            }
            set
            {
                OnProfileImageIdChanging(value);
                ReportPropertyChanging("ProfileImageId");
                _ProfileImageId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ProfileImageId");
                OnProfileImageIdChanged();
            }
        }
        private global::System.Int32 _ProfileImageId;
        partial void OnProfileImageIdChanging(global::System.Int32 value);
        partial void OnProfileImageIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Text
        {
            get
            {
                return _Text;
            }
            set
            {
                OnTextChanging(value);
                ReportPropertyChanging("Text");
                _Text = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Text");
                OnTextChanged();
            }
        }
        private global::System.String _Text;
        partial void OnTextChanging(global::System.String value);
        partial void OnTextChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 FurnitureId
        {
            get
            {
                return _FurnitureId;
            }
            set
            {
                if (_FurnitureId != value)
                {
                    OnFurnitureIdChanging(value);
                    ReportPropertyChanging("FurnitureId");
                    _FurnitureId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("FurnitureId");
                    OnFurnitureIdChanged();
                }
            }
        }
        private global::System.Int32 _FurnitureId;
        partial void OnFurnitureIdChanging(global::System.Int32 value);
        partial void OnFurnitureIdChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CmkFurnituresDbModel", "FK_Furnitures_Designers", "Designer")]
        public Designer Designer
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Designer>("CmkFurnituresDbModel.FK_Furnitures_Designers", "Designer").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Designer>("CmkFurnituresDbModel.FK_Furnitures_Designers", "Designer").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Designer> DesignerReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Designer>("CmkFurnituresDbModel.FK_Furnitures_Designers", "Designer");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Designer>("CmkFurnituresDbModel.FK_Furnitures_Designers", "Designer", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CmkFurnituresDbModel", "FK_Furnitures_FurnitureType", "FurnitureType")]
        public FurnitureType FurnitureType
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<FurnitureType>("CmkFurnituresDbModel.FK_Furnitures_FurnitureType", "FurnitureType").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<FurnitureType>("CmkFurnituresDbModel.FK_Furnitures_FurnitureType", "FurnitureType").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<FurnitureType> FurnitureTypeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<FurnitureType>("CmkFurnituresDbModel.FK_Furnitures_FurnitureType", "FurnitureType");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<FurnitureType>("CmkFurnituresDbModel.FK_Furnitures_FurnitureType", "FurnitureType", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CmkFurnituresDbModel", "FurnitureImages", "Image")]
        public EntityCollection<Image> Images
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Image>("CmkFurnituresDbModel.FurnitureImages", "Image");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Image>("CmkFurnituresDbModel.FurnitureImages", "Image", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CmkFurnituresDbModel", Name="FurnitureType")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class FurnitureType : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new FurnitureType object.
        /// </summary>
        /// <param name="furnitureTypeId">Initial value of the FurnitureTypeId property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        public static FurnitureType CreateFurnitureType(global::System.Int32 furnitureTypeId, global::System.String name)
        {
            FurnitureType furnitureType = new FurnitureType();
            furnitureType.FurnitureTypeId = furnitureTypeId;
            furnitureType.Name = name;
            return furnitureType;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 FurnitureTypeId
        {
            get
            {
                return _FurnitureTypeId;
            }
            set
            {
                if (_FurnitureTypeId != value)
                {
                    OnFurnitureTypeIdChanging(value);
                    ReportPropertyChanging("FurnitureTypeId");
                    _FurnitureTypeId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("FurnitureTypeId");
                    OnFurnitureTypeIdChanged();
                }
            }
        }
        private global::System.Int32 _FurnitureTypeId;
        partial void OnFurnitureTypeIdChanging(global::System.Int32 value);
        partial void OnFurnitureTypeIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CmkFurnituresDbModel", "FK_Furnitures_FurnitureType", "Furniture")]
        public EntityCollection<Furniture> Furnitures
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Furniture>("CmkFurnituresDbModel.FK_Furnitures_FurnitureType", "Furniture");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Furniture>("CmkFurnituresDbModel.FK_Furnitures_FurnitureType", "Furniture", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CmkFurnituresDbModel", Name="Image")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Image : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Image object.
        /// </summary>
        /// <param name="imageId">Initial value of the ImageId property.</param>
        /// <param name="path">Initial value of the Path property.</param>
        /// <param name="fileName">Initial value of the FileName property.</param>
        public static Image CreateImage(global::System.Int32 imageId, global::System.String path, global::System.String fileName)
        {
            Image image = new Image();
            image.ImageId = imageId;
            image.Path = path;
            image.FileName = fileName;
            return image;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ImageId
        {
            get
            {
                return _ImageId;
            }
            set
            {
                if (_ImageId != value)
                {
                    OnImageIdChanging(value);
                    ReportPropertyChanging("ImageId");
                    _ImageId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ImageId");
                    OnImageIdChanged();
                }
            }
        }
        private global::System.Int32 _ImageId;
        partial void OnImageIdChanging(global::System.Int32 value);
        partial void OnImageIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Path
        {
            get
            {
                return _Path;
            }
            set
            {
                OnPathChanging(value);
                ReportPropertyChanging("Path");
                _Path = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Path");
                OnPathChanged();
            }
        }
        private global::System.String _Path;
        partial void OnPathChanging(global::System.String value);
        partial void OnPathChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FileName
        {
            get
            {
                return _FileName;
            }
            set
            {
                OnFileNameChanging(value);
                ReportPropertyChanging("FileName");
                _FileName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FileName");
                OnFileNameChanged();
            }
        }
        private global::System.String _FileName;
        partial void OnFileNameChanging(global::System.String value);
        partial void OnFileNameChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CmkFurnituresDbModel", "FK_ImageSizes_Images", "ImageSize")]
        public EntityCollection<ImageSize> ImageSizes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ImageSize>("CmkFurnituresDbModel.FK_ImageSizes_Images", "ImageSize");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ImageSize>("CmkFurnituresDbModel.FK_ImageSizes_Images", "ImageSize", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CmkFurnituresDbModel", "FurnitureImages", "Furniture")]
        public EntityCollection<Furniture> Furnitures
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Furniture>("CmkFurnituresDbModel.FurnitureImages", "Furniture");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Furniture>("CmkFurnituresDbModel.FurnitureImages", "Furniture", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CmkFurnituresDbModel", Name="ImageSize")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ImageSize : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ImageSize object.
        /// </summary>
        /// <param name="imageId">Initial value of the ImageId property.</param>
        /// <param name="path">Initial value of the Path property.</param>
        /// <param name="fileName">Initial value of the FileName property.</param>
        /// <param name="width">Initial value of the Width property.</param>
        /// <param name="height">Initial value of the Height property.</param>
        /// <param name="imageSizeId">Initial value of the ImageSizeId property.</param>
        public static ImageSize CreateImageSize(global::System.Int32 imageId, global::System.String path, global::System.String fileName, global::System.Int32 width, global::System.Int32 height, global::System.Int32 imageSizeId)
        {
            ImageSize imageSize = new ImageSize();
            imageSize.ImageId = imageId;
            imageSize.Path = path;
            imageSize.FileName = fileName;
            imageSize.Width = width;
            imageSize.Height = height;
            imageSize.ImageSizeId = imageSizeId;
            return imageSize;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ImageId
        {
            get
            {
                return _ImageId;
            }
            set
            {
                OnImageIdChanging(value);
                ReportPropertyChanging("ImageId");
                _ImageId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ImageId");
                OnImageIdChanged();
            }
        }
        private global::System.Int32 _ImageId;
        partial void OnImageIdChanging(global::System.Int32 value);
        partial void OnImageIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Path
        {
            get
            {
                return _Path;
            }
            set
            {
                OnPathChanging(value);
                ReportPropertyChanging("Path");
                _Path = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Path");
                OnPathChanged();
            }
        }
        private global::System.String _Path;
        partial void OnPathChanging(global::System.String value);
        partial void OnPathChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FileName
        {
            get
            {
                return _FileName;
            }
            set
            {
                OnFileNameChanging(value);
                ReportPropertyChanging("FileName");
                _FileName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FileName");
                OnFileNameChanged();
            }
        }
        private global::System.String _FileName;
        partial void OnFileNameChanging(global::System.String value);
        partial void OnFileNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Width
        {
            get
            {
                return _Width;
            }
            set
            {
                OnWidthChanging(value);
                ReportPropertyChanging("Width");
                _Width = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Width");
                OnWidthChanged();
            }
        }
        private global::System.Int32 _Width;
        partial void OnWidthChanging(global::System.Int32 value);
        partial void OnWidthChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Height
        {
            get
            {
                return _Height;
            }
            set
            {
                OnHeightChanging(value);
                ReportPropertyChanging("Height");
                _Height = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Height");
                OnHeightChanged();
            }
        }
        private global::System.Int32 _Height;
        partial void OnHeightChanging(global::System.Int32 value);
        partial void OnHeightChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ImageSizeId
        {
            get
            {
                return _ImageSizeId;
            }
            set
            {
                if (_ImageSizeId != value)
                {
                    OnImageSizeIdChanging(value);
                    ReportPropertyChanging("ImageSizeId");
                    _ImageSizeId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ImageSizeId");
                    OnImageSizeIdChanged();
                }
            }
        }
        private global::System.Int32 _ImageSizeId;
        partial void OnImageSizeIdChanging(global::System.Int32 value);
        partial void OnImageSizeIdChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CmkFurnituresDbModel", "FK_ImageSizes_Images", "Image")]
        public Image Image
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Image>("CmkFurnituresDbModel.FK_ImageSizes_Images", "Image").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Image>("CmkFurnituresDbModel.FK_ImageSizes_Images", "Image").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Image> ImageReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Image>("CmkFurnituresDbModel.FK_ImageSizes_Images", "Image");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Image>("CmkFurnituresDbModel.FK_ImageSizes_Images", "Image", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CmkFurnituresDbModel", Name="Subscriber")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Subscriber : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Subscriber object.
        /// </summary>
        /// <param name="subscriberId">Initial value of the SubscriberId property.</param>
        /// <param name="email">Initial value of the Email property.</param>
        /// <param name="secret">Initial value of the Secret property.</param>
        public static Subscriber CreateSubscriber(global::System.Int32 subscriberId, global::System.String email, global::System.String secret)
        {
            Subscriber subscriber = new Subscriber();
            subscriber.SubscriberId = subscriberId;
            subscriber.Email = email;
            subscriber.Secret = secret;
            return subscriber;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SubscriberId
        {
            get
            {
                return _SubscriberId;
            }
            set
            {
                if (_SubscriberId != value)
                {
                    OnSubscriberIdChanging(value);
                    ReportPropertyChanging("SubscriberId");
                    _SubscriberId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("SubscriberId");
                    OnSubscriberIdChanged();
                }
            }
        }
        private global::System.Int32 _SubscriberId;
        partial void OnSubscriberIdChanging(global::System.Int32 value);
        partial void OnSubscriberIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Secret
        {
            get
            {
                return _Secret;
            }
            set
            {
                OnSecretChanging(value);
                ReportPropertyChanging("Secret");
                _Secret = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Secret");
                OnSecretChanged();
            }
        }
        private global::System.String _Secret;
        partial void OnSecretChanging(global::System.String value);
        partial void OnSecretChanged();

        #endregion
    
    }

    #endregion
    
}
